[tool.poetry]
name = "devopsufc"
version = "0.1.0"
description = ""
authors = ["MarcelloAle <marcelloalexandre2010@alu.ufc.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
mkdocs = "^1.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
