# Informações
site_name: DevOps UFC Quixadá
site_url: https://marcelloale.github.io/devopsufc/
site_author: Marcello Alexandre
site_description: >-
  Um site estático para compartilhamento de arquivos utilizados no grupo de estudos ufc quixada, hospedado no gh-pages.

# Plugins
plugins:
  - mkdocs-jupyter
  - search
  - mkdocs-video
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

# Configuração
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/infinity
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navegation.expand
    - navigation.tabs.sticky
    - navigation.tracking
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.date.min.js
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js

extra_css:
  - assets/css/tables.css

# Repository base
#repo_name: omadson/project-template
#repo_url: https://github.com/omadson/project-template
repo_name: marcelloale/devopsufc
repo_url: https://github.com/marcelloale/devopsufc